### ISSUE TITLE
Outdated links for CGR demo data

### ISSUE THREAD

**Issue by Gaidline** [iglesias/cgr_localization#3]
All three links to demo data from Readme are dead. According to custom generated doc, it should be changed to:
http://cobotrobots.com/data/cgr_localization/cobot2_ghc7_lidar.bag
http://cobotrobots.com/data/cgr_localization/cobot2_ghc7_kinect.bag
http://cobotrobots.com/data/cgr_localization/cobot2_nsh4_lidar.bag

**Comment by iglesias** [comment]
Updated, thanks a lot for reporting @Koralgoll!
